// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp5Bl-aETlshEoHPxYZHnBI_ifXKrl2Mk',
    appId: '1:919614908342:web:b2f22cc99f022611d68317',
    messagingSenderId: '919614908342',
    projectId: 'inkwiz-d7895',
    authDomain: 'inkwiz-d7895.firebaseapp.com',
    storageBucket: 'inkwiz-d7895.appspot.com',
    measurementId: 'G-MFZWE7JL2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM5XkLhQmT1zQnxnitiSeTmjRtbfNr7Ac',
    appId: '1:919614908342:android:49d31e6d3b745ff3d68317',
    messagingSenderId: '919614908342',
    projectId: 'inkwiz-d7895',
    storageBucket: 'inkwiz-d7895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2WLDqODLIbNy2TEPpWtBZN4moXRyulbc',
    appId: '1:919614908342:ios:2f58918c0b297347d68317',
    messagingSenderId: '919614908342',
    projectId: 'inkwiz-d7895',
    storageBucket: 'inkwiz-d7895.appspot.com',
    iosClientId: '919614908342-n96q3ps3aij78c6cgf9o1di9s6n2bm5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookaitool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2WLDqODLIbNy2TEPpWtBZN4moXRyulbc',
    appId: '1:919614908342:ios:19ffe59920835e7cd68317',
    messagingSenderId: '919614908342',
    projectId: 'inkwiz-d7895',
    storageBucket: 'inkwiz-d7895.appspot.com',
    iosClientId: '919614908342-u0fki513q70l24ag4vf6fq2didlq4qve.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookaitool.RunnerTests',
  );
}
